### ISSUE TITLE
jinja2.exceptions.TemplateSyntaxError: Expected an expression, got 'end of print statement'

### ISSUE THREAD

**Issue by Michael-Liao** [audreyr/cookiecutter#1071]
* Cookiecutter version: 1.6.0
* Template project url: https://github.com/Michael-Liao/cookiecutter-cmake/tree/feature/add-hook
* Python version: python 3.5
* Operating System: ubuntu16.04

### Description:
I created a cookiecutter from scatch for cmake. Everything is all good untill I added a post gen hook.
It spits out a lot of errors and the project is successfully generated. However the actions defined in the hook isn't executed.

### Error Message:

```
Traceback (most recent call last):
  File "/home/michael/.local/bin/cookiecutter", line 11, in <module>
    sys.exit(main())
  File "/home/michael/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/michael/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/michael/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/michael/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/michael/.local/lib/python3.5/site-packages/cookiecutter/cli.py", line 120, in main
    password=os.environ.get('COOKIECUTTER_REPO_PASSWORD')
  File "/home/michael/.local/lib/python3.5/site-packages/cookiecutter/main.py", line 94, in cookiecutter
    output_dir=output_dir
  File "/home/michael/.local/lib/python3.5/site-packages/cookiecutter/generate.py", line 376, in generate_files
    delete_project_on_failure
  File "/home/michael/.local/lib/python3.5/site-packages/cookiecutter/generate.py", line 236, in _run_hook_from_repo_dir
    run_hook(hook_name, project_dir, context)
  File "/home/michael/.local/lib/python3.5/site-packages/cookiecutter/hooks.py", line 144, in run_hook
    run_script_with_context(script, project_dir, context)
  File "/home/michael/.local/lib/python3.5/site-packages/cookiecutter/hooks.py", line 124, in run_script_with_context
    template = env.from_string(contents)
  File "/home/michael/.local/lib/python3.5/site-packages/jinja2/environment.py", line 880, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/home/michael/.local/lib/python3.5/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/michael/.local/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/michael/.local/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 20, in template
  File "/home/michael/.local/lib/python3.5/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/michael/.local/lib/python3.5/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/michael/.local/lib/python3.5/site-packages/jinja2/parser.py", line 875, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "/home/michael/.local/lib/python3.5/site-packages/jinja2/parser.py", line 637, in parse_tuple
    describe_token(self.stream.current))
  File "/home/michael/.local/lib/python3.5/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Expected an expression, got 'end of print statement'
```

**Comment by hackebrot** [comment]
Hi @Michael-Liao! 👋 

The error suggests that there is a problem with the [jinja2 template](http://jinja.pocoo.org/docs/2.10/) in your hook.

Looks like [this comment](https://github.com/Michael-Liao/cookiecutter-cmake/blob/feature/add-hook/hooks/post_gen_project.py#L20) is the source of the problem?

**Comment by pydanny** [comment]
Closing this issue as it appears to be a problem with `cookiecutter-cmake` rather than Cookiecutter itself. If I'm in error, please reopen this issue.
