### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by red8888** [audreyr/cookiecutter#1079]
* Cookiecutter version: Cookiecutter 1.6.0 from c:\users\ME\appdata\local\programs\python\python36-32\lib\site-packages (Python 3.6)
* Template project url: ALL
* Python version: Python 3.6
* Operating System: Win10

### Description:

Can use cookiecutter I get a weird error when trying to use a template.

cookiecutter gh:Pylons/pyramid-cookiecutter-starter --checkout 1.9-branch
Traceback (most recent call last):
  File "c:\users\MEEEE\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\MEEEE\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\MEEEE\AppData\Local\Programs\Python\Python36-32\Scripts\cookiecutter.exe\__main__.py", line 9, in <module>
  File "c:\users\MEEEE\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\MEEEE\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\MEEEE\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\MEEEE\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\MEEEE\appdata\local\programs\python\python36-32\lib\site-packages\cookiecutter\cli.py", line 120, in main
    password=os.environ.get('COOKIECUTTER_REPO_PASSWORD')
  File "c:\users\MEEEE\appdata\local\programs\python\python36-32\lib\site-packages\cookiecutter\main.py", line 63, in cookiecutter
    password=password
  File "c:\users\MEEEE\appdata\local\programs\python\python36-32\lib\site-packages\cookiecutter\repository.py", line 103, in determine_repo_dir
    no_input=no_input,
  File "c:\users\MEEEE\appdata\local\programs\python\python36-32\lib\site-packages\cookiecutter\vcs.py", line 99, in clone
    stderr=subprocess.STDOUT,
  File "c:\users\MEEEE\appdata\local\programs\python\python36-32\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "c:\users\MEEEE\appdata\local\programs\python\python36-32\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\MEEEE\appdata\local\programs\python\python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "c:\users\MEEEE\appdata\local\programs\python\python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by pydanny** [comment]
Does this problem occur just with `pyramid-cookiecutter-starter` or with other Cookiecutter templates?

**Comment by red8888** [comment]
All templates. I can run it with --help but anything with templates fails

**Comment by bradfox2** [comment]
@red8888 Did you ever figure this error out?  Happening to me on Win10 with cookiecutter and pyscaffold.
