### ISSUE TITLE
Paths longer than 256 characters don't work on Windows 7

### ISSUE THREAD

**Issue by akuntsch** [audreyr/cookiecutter#1098]
* Cookiecutter version: 1.6.0
* Python version: 3.7.0
* Operating System: Windows 7

### Description:

I'm trying to create a project from a cookiecutter template with long paths on Windows 7.

### What I've run:

I've run cookiecutter with a local template which contains very long paths exceeding 256 characters.

```cookiecutter.exe /path/to/local/template/folder```

Output: 

```
[Errno 2] No such file or directory: '{{cookiecutter.repo_name}}-this/is/a/really/long/path/that/exceeds/256/characters/{{cookiecutter.brand_lower}}/{{cookiecutter.brand_upper}}_my_excel_file.xlsx'
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\Scripts\cookiecutter.exe\__main__.py", line 9, in <module>
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\cookiecutter\cli.py", line 120, in main
    password=os.environ.get('COOKIECUTTER_REPO_PASSWORD')
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\cookiecutter\main.py", line 94, in cookiecutter
    output_dir=output_dir
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\cookiecutter\generate.py", line 364, in generate_files
    generate_file(project_dir, infile, context, env)
  File "c:\users\user\appdata\local\programs\python\python37-32\lib\site-packages\cookiecutter\generate.py", line 166, in generate_file
    tmpl = env.get_template(infile_fwd_slashes)
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\jinja2\loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: {{cookiecutter.repo_name}}-this/is/a/really/long/path/that/exceeds/256/characters/{{cookiecutter.brand_lower}}/{{cookiecutter.brand_upper}}_my_excel_file.xlsx
```

**Comment by akuntsch** [comment]
Just a note: the same template works in a Linux VM no problem.

**Comment by luzfcb** [comment]
@akuntsch this is not a cookiecutter bug, but a deliberate Windows limitation. Windows [limits the maximum path length to 255 characters [1]](https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file#maximum-path-length-limitation), but it's stupid enough to authorize you to create path larger than 255 characters in a variety of situations, however, those paths become inaccessible soon after.

the link [[1]](https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file#maximum-path-length-limitation), shows some solutions to the problem.

having said this, from my personal experience and personal opinion, unless you use microsoft technologies to develop your software, using Windows as a development machine makes your life much more complicated, because:

- The file system, by default, do not use Unicode as a character encoder, but the ugly "[Windows-1252](https://en.wikipedia.org/wiki/Windows-1252)". (I have a "fun" story with this, it involves a java software character encode bug (thanks Windows-1252), thousands of people at the door of your company (a brazilian government company) and television crew doing reporting. )
- CMD is a horrible piece of software compared to any Linux/BSD terminal emulator (WTH is so complicated to select, copy and paste on CMD ?)
- It's annoying to install C/C ++ compiler to compile Python extensions on Windows ... (although Anaconda Python made it easier in that case)
- I can say several other reasons, but I will stop here.

[1] https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file#maximum-path-length-limitation

**Comment by akuntsch** [comment]
@luzfcb 
> having said this, from my personal experience and personal opinion, unless you use microsoft technologies to develop your software, using Windows as a development machine makes your life much more complicated

I agree but sadly no way around it at my workplace.

> CMD is a horrible piece of software compared to any Linux/BSD terminal emulator (WTH is so complicated to select, copy and paste on CMD ?)

True, I use Git Bash which works ok for most things and also supports the long paths. Windows Explorer also seems to at least show the paths and lets me open files.

What about prefixing the paths with `\\?\` as noted on the page you linked?

**Comment by luzfcb** [comment]
@akuntsch 
> What about prefixing the paths with \\?\ as noted on the page you linked?

I do not have windows to test..

I do not have a solution ready for you, because I'm no longer forced to use Windows for several years.
if you have the opportunity to at least migrate to Windows 10, you can use WSL ( Windows Subsystem for Linux )

https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by akuntsch** [comment]
@luzfcb 

> I do not have windows to test..

I do :stuck_out_tongue:. I'll try to fix it myself if I have some time and iwill submit a PR if successful.

Windows 10 migration is underway at work but yea... soon:tm:

**Comment by akuntsch** [comment]
I stumbled upon a related [Python Issue](https://bugs.python.org/issue18199) which says that in Windows 10 the prefix is not needed anymore. So fixing this for earlier versions might not be worth it, so I'm closing the issue.
