### ISSUE TITLE
NotADirectoryError for files

### ISSUE THREAD

**Issue by akshaybabloo** [audreyr/cookiecutter#1099]
* Cookiecutter version: 1.6.0
* Template project url: Private
* Python version: 3.7
* Operating System: Windows 10

### Description:

I have a file as `Dockerfile.{{cookiecutter.project_name}}`, I am getting an error as `NotADirectoryError`. I am not sure what the problem is.

### What I've run:

```
(neucube) C:\Users\aksha\Documents\GitHub\neucube-cloud-cookiecutter\temp>cookiecutter C:\Users\aksha\Documents\GitHub\neucube-cloud-cookiecutter
project_name [some_name]: neucube
db_name [project_name]:
db_user [user_name]:
db_password [secret]:
db_port [5432]:
Traceback (most recent call last):
  File "c:\users\aksha\miniconda3\envs\neucube\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\aksha\miniconda3\envs\neucube\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\aksha\Miniconda3\envs\neucube\Scripts\cookiecutter.exe\__main__.py", line 9, in <module>
  File "c:\users\aksha\miniconda3\envs\neucube\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\aksha\miniconda3\envs\neucube\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\aksha\miniconda3\envs\neucube\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\aksha\miniconda3\envs\neucube\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\aksha\miniconda3\envs\neucube\lib\site-packages\cookiecutter\cli.py", line 120, in main
    password=os.environ.get('COOKIECUTTER_REPO_PASSWORD')
  File "c:\users\aksha\miniconda3\envs\neucube\lib\site-packages\cookiecutter\main.py", line 94, in cookiecutter
    output_dir=output_dir
  File "c:\users\aksha\miniconda3\envs\neucube\lib\site-packages\cookiecutter\generate.py", line 301, in generate_files
    with work_in(template_dir):
  File "c:\users\aksha\miniconda3\envs\neucube\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "c:\users\aksha\miniconda3\envs\neucube\lib\site-packages\cookiecutter\utils.py", line 71, in work_in
    os.chdir(dirname)
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\aksha\\Documents\\GitHub\\neucube-cloud-cookiecutter\\Dockefile.{{cookiecutter.project_name}}'
```

**Comment by heitorlessa** [comment]
You need to create a directory with that name and add your Dockerfile
inside:

{{cookiecutter.project_name}}/Dockerfile

Dockerfile.{{cookiecutter.project_name}} is a file and therefore the
exception raised - It’s not a directory
