### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80

### ISSUE THREAD

**Issue by dtunctuncer** [audreyr/cookiecutter#1169]
* Cookiecutter version:Cookiecutter 1.6.0 from /usr/local/lib/python3.7/site-packages (Python 3.7)
* Template project url:https://github.com/dtunctuncer/cookiecutter-test
* Python version:3.7
* Operating System: macOS Mojave 10.14.4 (18E226)

### Description:
I have been trying to create a new android template project I wanted to test and this what I get.

### What I've run:

```
cookiecutter kotlin-template
project_name [kotlin-template]: test
repo_name [test]: 
min_sdk [19]: 
target_sdk [28]: 
package_name [com.nodesagency.test]: com.dtunctuncer.test
version [1.0.0]: 
hockey_id_staging []: 
hockey_id_production []: 
Traceback (most recent call last):
  File "/usr/local/bin/cookiecutter", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cookiecutter/cli.py", line 120, in main
    password=os.environ.get('COOKIECUTTER_REPO_PASSWORD')
  File "/usr/local/lib/python3.7/site-packages/cookiecutter/main.py", line 94, in cookiecutter
    output_dir=output_dir
  File "/usr/local/lib/python3.7/site-packages/cookiecutter/generate.py", line 364, in generate_files
    generate_file(project_dir, infile, context, env)
  File "/usr/local/lib/python3.7/site-packages/cookiecutter/generate.py", line 166, in generate_file
    tmpl = env.get_template(infile_fwd_slashes)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 175, in get_source
    contents = f.read().decode(self.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 128: invalid start byte

```

**Comment by dtunctuncer** [comment]
I fix the problem but it is not actual fix 
I have changed the enconding type in this file `/usr/local/lib/python3.7/site-packages/jinja2/loaders.py` from `utf-8` to `unicode_escape`

**Comment by hackebrot** [comment]
Hi @dtunctuncer! 👋 

Would you mind raising this with the jinja2 project?
