### ISSUE TITLE
FileExistsError even though --overwrite-if-exists is specified.

### ISSUE THREAD

**Issue by raholler** [audreyr/cookiecutter#1176]
* Cookiecutter version: 1.6.0
* Template project url:https://github.com/hmgaudecker/econ-project-templates
* Python version:3.7
* Operating System: Windows 10

### Description:

I try to run cookiecutter from the command line such that it overwrites the project folder if it already exists.

### What I've run:
```
cookiecutter -f --no-input --output-dir example/python econ-project-templates
project_slug=python_example set_up_git=n create_conda_environment_with_name=x
```

But I get a FileExistsError even though - as far as I understand - -f should prevent this.

**Comment by insspb** [comment]
Confirmed

**Comment by sommersoft** [comment]
I'm sort of between projects, so I stumbled upon this issue while browsing. I've used cookiecutter in the past, so wanted to see if I could lend a hand.

I can also confirm this bug is valid on the above template. After testing against the `audreyr/cookiecutter-pypackage` template as a baseline, I've realized this only affects copying files that will not be rendered.

Here is the debug I got from running the above:
```shell
(venv) PS C:\Users\somme\Dev\cookie_dev\cookiecutter> py --version
Python 3.7.5

(venv) PS C:\Users\somme\Dev\cookie_dev\cookiecutter> cookiecutter -f -v --no-input --output-dir 
          ../example/python gh:hmgaudecker/econ-project-templates project_slug=python_example
          set_up_git=n create_conda_environment_with_name=x

DEBUG cookiecutter.utils: Making sure path exists: C:\Users\somme/.cookiecutters/
DEBUG cookiecutter.vcs: repo_dir is C:\Users\somme\.cookiecutters\econ-project-templates
DEBUG cookiecutter.main: context_file is C:\Users\somme\.cookiecutters\econ-project-templates\
      cookiecutter.json
DEBUG cookiecutter.generate: Context generated is OrderedDict( 
    # I removed most of this, but the following is relevant:
   ('_copy_without_render', ['.mywaflib', .... ]))

DEBUG cookiecutter.utils: Making sure path exists: C:\Users\somme/.cookiecutter_replay/
DEBUG cookiecutter.find: Searching C:\Users\somme\.cookiecutters\econ-project-templates for the
      project template.
DEBUG cookiecutter.find: The project template appears to be C:\Users\somme\.cookiecutters\
      econ-project-templates\{{cookiecutter.project_slug}}
DEBUG cookiecutter.generate: Generating project from C:\Users\somme\.cookiecutters\econ-project-
      templates\{{cookiecutter.project_slug}}...
DEBUG cookiecutter.generate: Rendered dir ..\example\python\python_example must exist in output_dir 
      ../example/python
DEBUG cookiecutter.generate: Output directory ..\example\python\python_example already exists,overwriting it
DEBUG cookiecutter.generate: Project directory is C:\Users\somme\Dev\cookie_dev\example\python\python_example
DEBUG cookiecutter.hooks: hooks_dir is C:\Users\somme\.cookiecutters\econ-project-templates\hooks
DEBUG cookiecutter.hooks: Running hook pre_gen_project
DEBUG cookiecutter.generate: Copying dir .mywaflib to C:\Users\somme\Dev\cookie_dev\example\python\
      python_example\.mywaflib without rendering
Traceback (most recent call last):
  File "C:\Users\somme\AppData\Local\Programs\Python\Python37\Scripts\cookiecutter-script.py", line 11, in <module>
    load_entry_point('cookiecutter', 'console_scripts', 'cookiecutter')()
  File "C:\Users\somme\AppData\Local\Programs\Python\Python37\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\somme\AppData\Local\Programs\Python\Python37\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\somme\AppData\Local\Programs\Python\Python37\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\somme\AppData\Local\Programs\Python\Python37\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\somme\dev\cookie_dev\cookiecutter\cookiecutter\cli.py", line 121, in main
    password=os.environ.get('COOKIECUTTER_REPO_PASSWORD')
  File "c:\users\somme\dev\cookie_dev\cookiecutter\cookiecutter\main.py", line 94, in cookiecutter
    output_dir=output_dir
  File "c:\users\somme\dev\cookie_dev\cookiecutter\cookiecutter\generate.py", line 328, in generate_files
    shutil.copytree(indir, outdir)
  File "C:\Users\somme\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 324, in copytree
    os.makedirs(dst)
  File "C:\Users\somme\AppData\Local\Programs\Python\Python37\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 
           'C:\\Users\\somme\\Dev\\cookie_dev\\example\\python\\python_example\\.mywaflib'
```

Buried in there, you can see the the `.mywaflib` directory is listed in the `_copy_without_render` context.

Looking at the traceback and the source, `os.makedirs()` seems to be the culprit, via ` shutil.copytree()`.

Per the Python 3.7 [docs](https://docs.python.org/3.7/library/shutil.html#shutil.copytree):
```
The destination directory, named by dst, must not already exist;
```

However, with the release of Python 3.8, `dirs_exist_ok` has been [added](https://docs.python.org/3.8/library/shutil.html#shutil.copytree). I assume because it now extends the `exist_ok` kwarg to `os.makedirs()`, which doesn't raise the exception if the dir exists:
```
dirs_exist_ok dictates whether to raise an exception in case dst or any missing parent directory already exists.
```

For a 3.7-and-earlier fix, the only "obvious" thing I can think of at the moment is to actually remove the non-rendered files from the destination, if the `overwrite-if-exists` argument is passed in. However, that introduces the possibility that a previous working version is wiped and leaves the user at a total loss.

Outside of that, it could just be a matter of updating documentation to better explain the actions and/or limitations of the `overwrite-if-exists` option.

**Comment by vrparte** [comment]
Hi, was looking into this issue, would like to work towards getting this issue closed
