### ISSUE TITLE
cookiecutter.json Decoding Error: Include File Path in Exception Message

### ISSUE THREAD

**Issue by rsyring** [audreyr/cookiecutter#355]
When the cookiecutter.json file is malformed, a traceback like the following is given:

```
rsyring@loftex:~/tmp$ cookiecutter ~/projects/cookiecutters/pyproject/ 
config_path is /home/rsyring/.cookiecutterrc
Traceback (most recent call last):
  File "/home/rsyring/.local/bin/cookiecutter", line 9, in <module>
    load_entry_point('cookiecutter==0.8.0', 'console_scripts', 'cookiecutter')()
  File "/home/rsyring/.local/lib/python2.7/site-packages/cookiecutter/main.py", line 171, in main
    cookiecutter(args.input_dir, args.checkout, args.no_input)
  File "/home/rsyring/.local/lib/python2.7/site-packages/cookiecutter/main.py", line 95, in cookiecutter
    extra_context=extra_context,
  File "/home/rsyring/.local/lib/python2.7/site-packages/cookiecutter/generate.py", line 43, in generate_context
    obj = json.load(file_handle, object_pairs_hook=OrderedDict)
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 4 column 1 (char 115)
```

It would be really nice if this Exception message was extended to include the path of the file in question.  For a new template developer, the added context would save some googling.

**Comment by rsyring** [comment]
new PR to replace this one: #388

**Comment by rsyring** [comment]
PR #388 replaces #358

**Comment by hackebrot** [comment]
#388 :white_check_mark:
