### ISSUE TITLE
Install package issue

### ISSUE THREAD

**Issue by jrborbars** [audreyr/cookiecutter#362]
I never used cookiecutter before, and I try to  install cookiecutter-flask (sloria). But when I'm do this, I get this error:

Traceback (most recent call last):
  File "/srv/http/gps/bin/cookiecutter", line 9, in <module>
    load_entry_point('cookiecutter==0.8.0', 'console_scripts', 'cookiecutter')()
  File "/srv/http/gps/local/lib/python2.7/site-packages/cookiecutter/main.py", line 171, in main
    cookiecutter(args.input_dir, args.checkout, args.no_input)
  File "/srv/http/gps/local/lib/python2.7/site-packages/cookiecutter/main.py", line 82, in cookiecutter
    no_input=no_input
  File "/srv/http/gps/local/lib/python2.7/site-packages/cookiecutter/vcs.py", line 92, in clone
    subprocess.check_call([repo_type, 'clone', repo_url], cwd=clone_to_dir)
  File "/usr/lib/python2.7/subprocess.py", line 506, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

I have an updated (to this day) Ubuntu 12.04 with python 2.7.3 installed and a fresh environment installed over virtualenv, with only the follow packages installed:
binaryornot==0.3.0
cookiecutter==0.8.0
Jinja2==2.7.3
MarkupSafe==0.23
mock==1.0.1
PyYAML==3.11

Any ideas?
Best regards,

**Comment by italomaia** [comment]
I just used this command:
```
cookiecutter https://github.com/sloria/cookiecutter-flask
```

And it worked.

**Comment by jrborbars** [comment]
This seems to be a virtualenv issue. I'm still not be able to install with cookiecutter, only with pip. Best regards.

**Comment by pydanny** [comment]
@jrborbars Cookiecutter is not an installation tool. Which prompts me to ask the following questions:

1. Can you share with us the command you used that triggered your error?
2. Are you running cookiecutter from within virtualenv?

**Comment by jrborbars** [comment]
@Italo Maia: The command is provided by cookiecutter-flask (after installation of cookiecutter with pip).
$ cookiecutter https://github.com/sloria/cookiecutter-flask.git
Only this command. And this is used inside a virtual environment (this is the recommended for installations with python language, no?) .

**Comment by pydanny** [comment]
Unfortunately I can't replicate the error.
