### ISSUE TITLE
problems with building the docs

### ISSUE THREAD

**Issue by jarrodwb** [audreyr/cookiecutter#375]
Hello,

I am having problems building the documentation. I am running Ubuntu 14.04.

``` bash
git clone git@github.com:audreyr/cookiecutter.git
cd cookiecutter
./setup.py build
./setup.py docs
```

Then I get and error I can't figure out.

Here is the full backtrace.

```
# Sphinx version: 1.2.2
# Python version: 3.4.0
# Docutils version: 0.11 release
# Jinja2 version: 2.7.2
# Loaded extensions:
#   docs.ccext from /home/jarrodwb/Desktop/cookie/cookiecutter/docs/ccext.py
#   sphinx.ext.autodoc from /usr/lib/python3/dist-packages/sphinx/ext/autodoc.py
#   sphinx.ext.viewcode from /usr/lib/python3/dist-packages/sphinx/ext/viewcode.py
#   sphinx.ext.intersphinx from /usr/lib/python3/dist-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.pngmath from /usr/lib/python3/dist-packages/sphinx/ext/pngmath.py
#   sphinx.ext.doctest from /usr/lib/python3/dist-packages/sphinx/ext/doctest.py
#   sphinx.ext.oldcmarkup from /usr/lib/python3/dist-packages/sphinx/ext/oldcmarkup.py
#   sphinx.ext.ifconfig from /usr/lib/python3/dist-packages/sphinx/ext/ifconfig.py
#   sphinx.ext.todo from /usr/lib/python3/dist-packages/sphinx/ext/todo.py
#   sphinx.ext.coverage from /usr/lib/python3/dist-packages/sphinx/ext/coverage.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/cmdline.py", line 254, in main
    app.build(force_all, filenames)
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 212, in build
    self.builder.build_update()
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 214, in build_update
    'out of date' % len(to_build))
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 234, in build
    purple, length):
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 134, in status_iterator
    for item in iterable:
  File "/usr/lib/python3/dist-packages/sphinx/environment.py", line 477, in update_generator
    self.read_doc(docname, app=app)
  File "/usr/lib/python3/dist-packages/sphinx/environment.py", line 624, in read_doc
    pub.publish()
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/usr/lib/python3/dist-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/usr/lib/python3/dist-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2962, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 328, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 396, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 283, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2727, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 328, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 396, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 283, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2300, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2312, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2055, in directive
    directive_class, match, type_name, option_presets)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2104, in run_directive
    result = directive_instance.run()
  File "/home/jarrodwb/Desktop/cookie/cookiecutter/docs/ccext.py", line 33, in run
    self.process_actions()
  File "/home/jarrodwb/Desktop/cookie/cookiecutter/docs/ccext.py", line 22, in process_actions
    parser = main._get_parser()
AttributeError: 'module' object has no attribute '_get_parser'
```

Any ideas?
Thanks

**Comment by michaeljoseph** [comment]
@jarrodwb It looks like building the documentation needs some.... documentation
AFAIK `pip install sphinx && make docs` is the way to go.

**Comment by pydanny** [comment]
Looks like we have a similar problem on RTD. I'll look into it.

**Comment by pydanny** [comment]
@michaeljoseph Seems like the conversion to click broke Sphinx because https://github.com/audreyr/cookiecutter/blob/master/docs/ccext.py was expecting the old design. See #391
