### ISSUE TITLE
Why I use cookiecutter to clone git responsitory always said "No such file and directory: u'/my/home/.cookiecutters/myproject/cookiecutter.json'?

### ISSUE THREAD

**Issue by zhaozhiming** [audreyr/cookiecutter#497]
HI ALL,
I'm newer to cookiecutter, when I use cookiecutter first time, it always report error as follow:
Please help. Thanks

```
You've cloned /xxxxx before. Is it okay to delete and re-clone it? [Y/n] Y
Cloning into 'python_lesson'...
remote: Counting objects: 3, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
Checking connectivity... done.
Traceback (most recent call last):
  File "/usr/local/bin/cookiecutter", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/cookiecutter/cli.py", line 70, in main
    cookiecutter(template, checkout, no_input)
  File "/Library/Python/2.7/site-packages/cookiecutter/main.py", line 92, in cookiecutter
    extra_context=extra_context,
  File "/Library/Python/2.7/site-packages/cookiecutter/generate.py", line 43, in generate_context
    file_handle = open(context_file)
IOError: [Errno 2] No such file or directory: u'/my/home/.cookiecutters/myproject/cookiecutter.json'

```

**Comment by luzfcb** [comment]
@zhaozhiming has full certainty that the repository you tried to clone with `cookiecutter` has a file named `cookiecutter.json` in the root directory of repository ?

**Comment by hackebrot** [comment]
Hi @zhaozhiming!

Cookiecutter requires a template to have two things:

1. a file named ``cookiecutter.json`` that defines variables and the corresponding default values
1. a folder that is templated, f.i. ``{{cookiecutter.repo_name}}``

There are a few tutorials which you may want to read at http://cookiecutter.readthedocs.org/en/latest/tutorials.html or you could have a look at other templates that are featured on the README file of this project.

Hope this helps! :bow:
