### ISSUE TITLE
Sphinx docs build fails

### ISSUE THREAD

**Issue by hackebrot** [audreyr/cookiecutter#502]
I am afraid #264 is back... :worried: 

@audreyr @pydanny any idea whether the latest release of **binaryornot** may cause the following error on **Read the Docs**?

```bash
Running Sphinx v1.3.1
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cookiecutter/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cookiecutter/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 143, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cookiecutter/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 433, in setup_extension
    err)
ExtensionError: Could not import extension docs.ccext (exception: No module named binaryornot.check)

Extension error:
Could not import extension docs.ccext (exception: No module named binaryornot.check)
```

Last docs build success was a week ago, please see [readthedocs builds] (https://readthedocs.org/projects/cookiecutter/builds/).

**Comment by pydanny** [comment]
Fixed. I told `rtfd` to use `python setup.py` for determining requirements.

**Comment by hackebrot** [comment]
Many thanks @pydanny! :bow:
