### ISSUE TITLE
markupsafe missing dependency during install

### ISSUE THREAD

**Issue by seanvetter** [audreyr/cookiecutter#570]
OS: Ubuntu 14.04
Version: 

``` sh
$ cookiecutter --version
Cookiecutter 1.2.1 from /usr/local/lib/python2.7/dist-packages (Python 2.7)
```
### Problem

Fresh install of cookiecutter using pip and I'm seeing this error when trying to use it.
pip installing markupsafe fixes the problem but it would be best if this dependency was taken
care of for the user.
### Output

$ cookiecutter 
Traceback (most recent call last):
  File "/usr/local/bin/cookiecutter", line 7, in <module>
    from cookiecutter.cli import main
  File "/usr/local/lib/python2.7/dist-packages/cookiecutter/cli.py", line 18, in <module>
    from cookiecutter.main import cookiecutter
  File "/usr/local/lib/python2.7/dist-packages/cookiecutter/main.py", line 21, in <module>
    from .prompt import prompt_for_config
  File "/usr/local/lib/python2.7/dist-packages/cookiecutter/prompt.py", line 17, in <module>
    from jinja2.environment import Environment
  File "/usr/local/lib/python2.7/dist-packages/jinja2/**init**.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 13, in <module>
    from jinja2 import nodes
  File "/usr/local/lib/python2.7/dist-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/usr/local/lib/python2.7/dist-packages/jinja2/utils.py", line 531, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: No module named markupsafe

**Comment by hackebrot** [comment]
Thanks for reporting this @seanvetter!

:sob: https://github.com/mitsuhiko/jinja2/blob/master/setup.py#L70

**Comment by hackebrot** [comment]
I don't think this is still an issue. Please ping me if that's not the case and I'll re-open this. Thanks 🙇
