### ISSUE TITLE
When directory name resolves to empty string cookiecutter tries to put things in root of filesystem

### ISSUE THREAD

**Issue by johtso** [audreyr/cookiecutter#586]
When using the force flag to get around this issue https://github.com/audreyr/cookiecutter/issues/585 I got a traceback saying that cookiecutter does not have permission to create a file.

Turns out that this was because the package directory name resolved to an empty string.

It would seem that this behaviour could be rather dangerous..

```
Traceback (most recent call last):
  File "/Users/human/.virtualenvs/service-sandbox/bin/cookiecutter", line 11, in <module>
    sys.exit(main())
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/cookiecutter/cli.py", line 100, in main
    config_file=user_config
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/cookiecutter/main.py", line 140, in cookiecutter
    output_dir=output_dir
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/cookiecutter/generate.py", line 327, in generate_files
    generate_file(project_dir, infile, context, env)
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/cookiecutter/generate.py", line 177, in generate_file
    with io.open(outfile, 'w', encoding='utf-8') as fh:
IOError: [Errno 13] Permission denied: '/__init__.py'
```

**Comment by pydanny** [comment]
Can you please provide the following:

1. The exact way you invoked Cookiecutter. ex. `cookiecutter <MY-PROJECT-LOCATION`.
2. Your operating system.
3. If possible, the URL location of the Cookiecutter template you are trying to use.

**Comment by johtso** [comment]
Here's a minimal example that shows the behaviour https://github.com/johtso/cookiecutter-paths-bug

```
❯ cookiecutter -o ../tmp_cookiecutter_output . -f
test [foo]:
Traceback (most recent call last):
  File "/usr/local/bin/cookiecutter", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/cookiecutter/cli.py", line 100, in main
    config_file=user_config
  File "/usr/local/lib/python2.7/site-packages/cookiecutter/main.py", line 140, in cookiecutter
    output_dir=output_dir
  File "/usr/local/lib/python2.7/site-packages/cookiecutter/generate.py", line 327, in generate_files
    generate_file(project_dir, infile, context, env)
  File "/usr/local/lib/python2.7/site-packages/cookiecutter/generate.py", line 177, in generate_file
    with io.open(outfile, 'w', encoding='utf-8') as fh:
IOError: [Errno 13] Permission denied: '/test.txt'
```

The root of this bug is here: https://github.com/audreyr/cookiecutter/blob/master/cookiecutter/generate.py#L146

`infile` is something like `'{{cookiecutter.not_defined}}/test.txt'` which is then rendered to `'/test.txt'`.

Consequently doing an `os.path.join` with the `project_dir` results in `'/test.txt'`
