### ISSUE TITLE
cookiecutter attempts to render .pyc files and throws unclear exception

### ISSUE THREAD

**Issue by johtso** [audreyr/cookiecutter#589]
You end up with an exception something like this:

```
  File "/Users/human/.virtualenvs/service-sandbox/bin/cookiecutter", line 4, in <module>
    import re
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/cookiecutter/cli.py", line 100, in main
    config_file=user_config
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/cookiecutter/main.py", line 140, in cookiecutter
    output_dir=output_dir
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/cookiecutter/generate.py", line 327, in generate_files
    generate_file(project_dir, infile, context, env)
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/cookiecutter/generate.py", line 167, in generate_file
    tmpl = env.get_template(infile_fwd_slashes)
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/jinja2/loaders.py", line 175, in get_source
    contents = f.read().decode(self.encoding)
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf3 in position 1: invalid continuation byte
```

And have to jump into `pdb` to work out what file is causing the problem.

**Comment by pydanny** [comment]
The problem is that `.pyc` files are binary files that *shouldn't* be in your repo. They should be marked in the `.gitignore` module. Which means you need to get `*.pyc` into your `.gitignore`. :wink: 

That said, Cookiecutter shouldn't be failing on this issue, especially as https://github.com/audreyr/binaryornot should be catching this problem. Which is why @audreyr opened a related ticket in that project.

**Comment by johtso** [comment]
:+1:

Not sure how the `.pyc` ended up in my template directory, they're definitely .gitignored but I must have inadvertently run/imported one of the files at some point. Using something like binaryornot seems like a great idea.

**Comment by johtso** [comment]
I'm struggling to reproduce this issue. If anyone wants to try their hand at it, here's the full traceback along with the repr of the file contents:

```
~/C/c/somedirectory vservice-sandbox
❯ python -m pdb /Users/human/.virtualenvs/service-sandbox/bin/cookiecutter -o somewhere ../service-template
> /Users/human/.virtualenvs/service-sandbox/bin/cookiecutter(4)<module>()
-> import re
(Pdb) c
project_name [Some Service]:
repo_name [some-service]:
pkg_name [some_service]:
author [CrowdScores]:
email [devs@crowdscores.com]:
version [0.0.1]:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "/Users/human/.virtualenvs/service-sandbox/bin/cookiecutter", line 4, in <module>
    import re
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/cookiecutter/cli.py", line 100, in main
    config_file=user_config
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/cookiecutter/main.py", line 140, in cookiecutter
    output_dir=output_dir
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/cookiecutter/generate.py", line 327, in generate_files
    generate_file(project_dir, infile, context, env)
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/cookiecutter/generate.py", line 167, in generate_file
    tmpl = env.get_template(infile_fwd_slashes)
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/site-packages/jinja2/loaders.py", line 175, in get_source
    contents = f.read().decode(self.encoding)
  File "/Users/human/.virtualenvs/service-sandbox/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf3 in position 1: invalid continuation byte
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /Users/human/.virtualenvs/service-sandbox/lib/python2.7/encodings/utf_8.py(16)decode()
-> return codecs.utf_8_decode(input, errors, True)
(Pdb) input
'\x03\xf3\r\n\xb2?\xa5Uc\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00@\x00\x00\x00s\x04\x00\x00\x00d\x00\x00S(\x01\x00\x00\x00N(\x00\x00\x00\x00(\x00\x00\x00\x00(\x00\x00\x00\x00(\x00\x00\x00\x00s;\x00\x00\x00/apps/orchestration/code/orchestration/settings/__init__.pyt\x08\x00\x00\x00<module>\x01\x00\x00\x00s\x00\x00\x00\x00'
```

**Comment by hackebrot** [comment]
``apps/orchestration/code/orchestration/settings/__init__.pyt``? Another binary file?

**Comment by johtso** [comment]
I think the `t` is just a bit of binary data after the path to the original `.py` file.

**Comment by johtso** [comment]
@hackebrot finally managed to reproduce the issue https://github.com/audreyr/binaryornot/pull/23

**Comment by sdsaati** [comment]
Fixed: by using this at the beginning of my cookiecutter.json file:
```json
"_copy_without_render": [
    "*.o",
    "*.exe",
    "*.so",
   "*.pyc",
    "*.a",
    "*.lib",
    "*.obj",
    "*.dll",
    "*.png",
    "*.jpg"
  ],
```
