### ISSUE TITLE
Missing PyYAML depedency

### ISSUE THREAD

**Issue by andreyfedoseev** [audreyr/cookiecutter#605]
Fresh installation of v1.3 on OS X 10.11 with pipsi fails to run with the following error:

```
$ pipsi install cookiecutter
$ cookiecutter
Traceback (most recent call last):
  File "/Users/username/.local/bin/cookiecutter", line 8, in <module>
    load_entry_point('cookiecutter==1.3.0', 'console_scripts', 'cookiecutter')()
  File "/Users/username/.local/venvs/cookiecutter/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 318, in load_entry_point
  File "/Users/username/.local/venvs/cookiecutter/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 2221, in load_entry_point
  File "/Users/username/.local/venvs/cookiecutter/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 1954, in load
  File "/Users/username/.local/venvs/cookiecutter/lib/python2.7/site-packages/cookiecutter/cli.py", line 18, in <module>
    from cookiecutter.config import USER_CONFIG_PATH
  File "/Users/username/.local/venvs/cookiecutter/lib/python2.7/site-packages/cookiecutter/config.py", line 20, in <module>
    import yaml
ImportError: No module named yaml
```

Installing PyYAML to the virtualenv solves the problem.

**Comment by hackebrot** [comment]
Hey @andreyfedoseev! :wave: 

What if you install via ``pip`` instead? Is it running into the same error?

**Comment by andreyfedoseev** [comment]
> What if you install via pip instead? Is it running into the same error?

Yes, same error:

```
$ cd /tmp
$ virtualenv virtualenv
$ source virtualenv/bin/activate
$ pip install cookiecutter
$ ./virtualenv/bin/cookiecutter
Traceback (most recent call last):
  File "./virtualenv/bin/cookiecutter", line 8, in <module>
    load_entry_point('cookiecutter==1.3.0', 'console_scripts', 'cookiecutter')()
  File "/private/tmp/virtualenv/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 318, in load_entry_point
  File "/private/tmp/virtualenv/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 2221, in load_entry_point
  File "/private/tmp/virtualenv/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 1954, in load
  File "/private/tmp/virtualenv/lib/python2.7/site-packages/cookiecutter/cli.py", line 18, in <module>
    from cookiecutter.config import USER_CONFIG_PATH
  File "/private/tmp/virtualenv/lib/python2.7/site-packages/cookiecutter/config.py", line 20, in <module>
    import yaml
ImportError: No module named yaml
```

I think I can clearly see why this happens. `PyYAML` is not specified as a requirement in `setup.py`, except for Win environment.

**Comment by hackebrot** [comment]
That is correct, however ``'ruamel.yaml>=0.10.12'`` is [declared as a requirement](https://github.com/audreyr/cookiecutter/blob/master/setup.py#L70). :worried:

**Comment by andreyfedoseev** [comment]
FYI, I have `setuptools==0.6c11`

**Comment by hackebrot** [comment]
``setuptools (16.0)`` :smile_cat:

**Comment by andreyfedoseev** [comment]
Since I use Vagrant for all development, I guess I never bothered to upgrade `setuptools` installed in my host OS. Feel free to close the issue if you think that it's a corner case that doesn't worth attention.

**Comment by hackebrot** [comment]
Does it work with a newer version of setuptools though?

**Comment by andreyfedoseev** [comment]
Yes, it does:

```
Collecting ruamel.base>=1.0.0 (from ruamel.yaml>=0.10.12->cookiecutter)
  Downloading ruamel.base-1.0.0-py2-none-any.whl
Collecting ruamel.ordereddict (from ruamel.yaml>=0.10.12->cookiecutter)
  Downloading ruamel.ordereddict-0.4.9.tar.gz (53kB)
    100% |████████████████████████████████| 57kB 3.1MB/s
```

And these progress bars...like the future is now!

**Comment by hackebrot** [comment]
Ok cool :smile_cat:
