### ISSUE TITLE
Unhelpful error if template branch is specified incorrectly

### ISSUE THREAD

**Issue by freakboy3742** [audreyr/cookiecutter#776]
* Cookiecutter version: 1.4.0
* Template project url: https://github.com/pybee/Python-Android-template
* Python version: 2.7
* Operating System: macOS

### Description:

If you specify a template project URL that exists, but a branch that does *not* exist, the `git clone` command fails, raising an exception.

This is entirely expected. However, the error message that is raised isn't especially helpful - it's a simple dump of the subprocess failure, rather than something pointing at the underlying problem.

### What I've run:

The problem is easy to reproduce - specify a valid template URL, but a branch name that doesn't exist. In this example, I'm using Python-Android-template, with the non-existent 2.7 branch.

    $ cookiecutter https://github.com/pybee/Python-Android-template --checkout 2.7
    You've cloned /Users/rkm/.cookiecutters/Python-Android-template before. Is it okay to delete and re-clone it? [yes]: 
    Cloning into 'Python-Android-template'...
    remote: Counting objects: 174, done.
    remote: Total 174 (delta 0), reused 0 (delta 0), pack-reused 174
    Receiving objects: 100% (174/174), 75.87 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (64/64), done.
    Checking connectivity... done.
    error: pathspec '2.7' did not match any file(s) known to git.
    Traceback (most recent call last):
      File "setup.py", line 56, in <module>
        test_suite='tests'
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Users/rkm/projects/beeware/briefcase/briefcase/app.py", line 193, in run
        self.generate_app_template()
      File "/Users/rkm/projects/beeware/briefcase/briefcase/app.py", line 110, in generate_app_template
        'month': date.today().strftime('%B'),
      File "/Users/rkm/.virtualenvs/briefcase/lib/python2.7/site-packages/cookiecutter/main.py", line 107, in cookiecutter
        no_input=no_input
      File "/Users/rkm/.virtualenvs/briefcase/lib/python2.7/site-packages/cookiecutter/vcs.py", line 122, in clone
        cwd=repo_dir)
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '[u'git', u'checkout', '2.7']' returned non-zero exit status 1

The message `error: pathspec '2.7' did not match any file(s) known to git.` is contained higher up in the stack trace; a public facing error message that said this would be more helpful than details about non-zero exit status of the subprocess. 

I've also tried invoking this directly via the API:

    from cookiecutter.main import cookiecutter
    cookiecutter(
            'https://github.com/pybee/Python-Android-template',
            no_input=True,
            checkout='%s.%s' % (sys.version_info.major, sys.version_info.minor),
            extra_context={
                'app_name': self.distribution.get_name(),
                'formal_name': self.formal_name,
                'organization_name': self.organization_name,
                'dir_name': self.dir,
                'bundle': self.bundle,
                'year': date.today().strftime('%Y'),
                'month': date.today().strftime('%B'),
            }
        )

Again, this raises a subprocess exception, rather than something more meaningful that could be caught and reported.

**Comment by hackebrot** [comment]
Thank you @freakboy3742 for reporting this! 🙇
