### ISSUE TITLE
I can't figure out how to run cookiecutter with my project

### ISSUE THREAD

**Issue by lukeschlather** [audreyr/cookiecutter#829]
* Cookiecutter version: 1.4.0
* Template project url: https://github.com/lukeschlather/cookiecutter-test
* Python version: 3.5
* Operating System: Ubuntu 16.04

### Description:

I have a .cookiecutterrc that looks like this:
default_context:
    team_name: "Myteam"
    team_email: "myteam@gmail.com"

I'm modelling my commands off of the example in the readme that goes:

Inject extra context with command-line arguments:

    $ cookiecutter --no-input gh:msabramo/cookiecutter-supervisor program_name=foobar startsecs=10

### What I've run:

     cd

    $ git clone https://github.com/lukeschlather/cookiecutter-test
    
    $ cookiecutter --no-input ~/cookiecutter-python3/ package_name="Cookiecutter Test"
    Usage: cookiecutter [OPTIONS] TEMPLATE
    
    Error: Got unexpected extra argument (package_name=Cookiecutter Test)
    
    $ cookiecutter --no-input ~/cookiecutter-python3/ package_name="Cookiecutter Test"
    Usage: cookiecutter [OPTIONS] TEMPLATE
    
    Error: Got unexpected extra argument (package_name=Cookiecutter Test)
    
    $ cookiecutter --no-input ~/cookiecutter-python3/ 
    Traceback (most recent call last):
      File "/home/luke/energysavvy/virtualenv/bin/cookiecutter", line 11, in <module>
        load_entry_point('cookiecutter', 'console_scripts', 'cookiecutter')()
      File "/home/luke/energysavvy/virtualenv-py35/lib/python3.5/site-packages/click/core.py", line 716, in __call__
        return self.main(*args, **kwargs)
      File "/home/luke/energysavvy/virtualenv-py35/lib/python3.5/site-packages/click/core.py", line 696, in main
        rv = self.invoke(ctx)
      File "/home/luke/energysavvy/virtualenv-py35/lib/python3.5/site-packages/click/core.py", line 889, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/luke/energysavvy/virtualenv-py35/lib/python3.5/site-packages/click/core.py", line 534, in invoke
        return callback(*args, **kwargs)
      File "/home/luke/energysavvy/virtualenv-py35/lib/python3.5/site-packages/cookiecutter/cli.py", line 106, in main
        config_file=user_config
      File "/home/luke/energysavvy/virtualenv-py35/lib/python3.5/site-packages/cookiecutter/main.py", line 144, in cookiecutter
        output_dir=output_dir
      File "/home/luke/energysavvy/virtualenv-py35/lib/python3.5/site-packages/cookiecutter/generate.py", line 253, in generate_files
        template_dir = find_template(repo_dir)
      File "/home/luke/energysavvy/virtualenv-py35/lib/python3.5/site-packages/cookiecutter/find.py", line 42, in find_template
        raise NonTemplatedInputDirException
    cookiecutter.exceptions.NonTemplatedInputDirException
    
    $ cookiecutter /tmp/cookiecutter-test/
    python_version [py34]: 
    artifact_type [python]: 
    author [EnergySavvy]: 
    starting_version ['0.1' + os.environ.get('BUILD_NUMBER', '0')]: 
    url [http://www.energysavvy.com/]: 
    project_name [REPLACEME]: Cookiecutter Test
    project_slug [cookiecutter_test]: 
    Traceback (most recent call last):
      File "/home/luke/energysavvy/virtualenv/bin/cookiecutter", line 11, in <module>
        load_entry_point('cookiecutter', 'console_scripts', 'cookiecutter')()
      File "/home/luke/energysavvy/virtualenv-py35/lib/python3.5/site-packages/click/core.py", line 716, in __call__
        return self.main(*args, **kwargs)
      File "/home/luke/energysavvy/virtualenv-py35/lib/python3.5/site-packages/click/core.py", line 696, in main
        rv = self.invoke(ctx)
      File "/home/luke/energysavvy/virtualenv-py35/lib/python3.5/site-packages/click/core.py", line 889, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/luke/energysavvy/virtualenv-py35/lib/python3.5/site-packages/click/core.py", line 534, in invoke
        return callback(*args, **kwargs)
      File "/home/luke/energysavvy/virtualenv-py35/lib/python3.5/site-packages/cookiecutter/cli.py", line 106, in main
        config_file=user_config
      File "/home/luke/energysavvy/virtualenv-py35/lib/python3.5/site-packages/cookiecutter/main.py", line 144, in cookiecutter
        output_dir=output_dir
      File "/home/luke/energysavvy/virtualenv-py35/lib/python3.5/site-packages/cookiecutter/generate.py", line 253, in generate_files
        template_dir = find_template(repo_dir)
      File "/home/luke/energysavvy/virtualenv-py35/lib/python3.5/site-packages/cookiecutter/find.py", line 42, in find_template
        raise NonTemplatedInputDirException
    cookiecutter.exceptions.NonTemplatedInputDirException

**Comment by hackebrot** [comment]
Hey @lukeschlather! 👋 

We haven't released this feature yet 😢 

See https://github.com/audreyr/cookiecutter/issues/799#issuecomment-241128185

**Comment by lukeschlather** [comment]
Ah. that explains that. What is NonTemplatedInputDirException?

**Comment by hackebrot** [comment]
It's raised when your template does not contain a directory which has a name like the following:

``{{cookiecutter.project_slug}}`` while ``project_slug`` can be w/e you want to name the variable.

**Comment by lukeschlather** [comment]
Does cookiecutter really need to enforce that? That seems like an
unnecessary pythonism. I'm writing Python so I'll just conform to the
convention, but in principle that might be inappropriate for other
languages. For example, I was thinking about using this for our NPM /
JavaScript packages as well, and the convention there doesn't require any
such directory to get a buildable package.

**Comment by lukeschlather** [comment]
Nevermind, I see now.

**Comment by hackebrot** [comment]
Happy you find cookiecutter useful. 😉

**Comment by kuroneko25** [comment]
I tried the code on master branch but it seems I have to define the variable in `cookiecutter.json`. For example I have something like this:
```
{
  "var1": "value1",
  "var2": "value2"
}
```
And if I then call cookiecuter like this `cookiecutter --no-input mytemplate var3=value3` it throws the exception `Error message: 'dict object' has no attribute 'var3'` unless I also define var3 in cookiecutter.json

**Comment by hackebrot** [comment]
Hi @kuroneko25! 👋 

That's intended behavior, you need to define a default value for ``var3`` in cookiecutter.json.

**Comment by cal97g** [comment]
Basically what nobody will actually come out and say is you need a directory structure like this:
```
 - template
      - cookiecutter.json
      - somefolder
            - filea.txt
      - some_file.py
```

Your cookiecutter.json needs to be in the template root
