### ISSUE TITLE
Symlinks become normal directories when cookiecutter is run

### ISSUE THREAD

**Issue by pjbull** [audreyr/cookiecutter#865]
* Cookiecutter version: master
* Template project url: 
* Python version: 3.5
* Operating System: OSX

### Description:

Symlinks within cookiecutter templates are copied as directories rather than as symlinks.

### What I've run:

Here's a cookiecutter template with just the `name` variable in `cookiecutter.json`:
```
12:42 $ tree symlink-cc/
symlink-cc/
├── cookiecutter.json
└── {{\ cookiecutter.name\ }}
    ├── original
    │   └── afile.txt
    └── symlink -> original
```

I can successfully run cookiecutter.
```
12:38 $ cookiecutter symlink-cc
name [pjb]: pjb
```

In the output, the symlink turns into a standard directory.
```
12:42 $ tree pjb/
pjb/
├── original
│   └── afile.txt
└── symlink
```

Working on a PR that should fix this.

**Comment by michaeljoseph** [comment]
Nice catch @pjbull! We look forward to your PR 😃

**Comment by davidwtbuxton** [comment]
What I would like is support for copying all symlinks as-is, not just symlinks to existing directories.

My use case is I have symlinks in the cooiecutter template that use relative paths to point to directories that do not exist (specifically, to directories that will be created by `npm install` in a new project).

In that situation, symlinks are added to os.walk's files list (not dirs list), and cookiecutter stops with an IOError exception when going to read the symlink's target.

```
Traceback (most recent call last):
  File "/Users/david/venv/bin/cookiecutter", line 11, in <module>
    load_entry_point('cookiecutter==1.5.1', 'console_scripts', 'cookiecutter')()
  File "/Users/david/venv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/david/venv/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/david/venv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/david/venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/david/venv/lib/python2.7/site-packages/cookiecutter/cli.py", line 123, in main
    default_config=default_config,
  File "/Users/david/venv/lib/python2.7/site-packages/cookiecutter/main.py", line 91, in cookiecutter
    output_dir=output_dir
  File "/Users/david/venv/lib/python2.7/site-packages/cookiecutter/generate.py", line 349, in generate_files
    generate_file(project_dir, infile, context, env)
  File "/Users/david/venv/lib/python2.7/site-packages/cookiecutter/generate.py", line 153, in generate_file
    if is_binary(infile):
  File "/Users/david/venv/lib/python2.7/site-packages/binaryornot/check.py", line 24, in is_binary
    chunk = get_starting_chunk(filename)
  File "/Users/david/venv/lib/python2.7/site-packages/binaryornot/helpers.py", line 32, in get_starting_chunk
    with open(filename, 'rb') as f:
IOError: [Errno 2] No such file or directory: u'{{ cookiecutter.static_dir }}/src/bulma'
```

This is Python 2.7, current master of cookiecutter ([a000a8f236a79b7d2dbffc6e945fcd69007a9baf][1]).

[1]: https://github.com/audreyr/cookiecutter/tree/a000a8f236a79b7d2dbffc6e945fcd69007a9baf

**Comment by bittner** [comment]
According to my analysis the culprit of this behavior is [`shutil.copytree`](https://github.com/audreyr/cookiecutter/blob/master/cookiecutter/generate.py#L314). In Python 3.3 this function also causes the following error (for a symlink `framework` to a directory):
``` python
Traceback (most recent call last):
  File "/home/peter/.virtualenvs/name-of-the-project/bin/cookiecutter", line 11, in <module>
    sys.exit(main())
  File "/home/peter/.virtualenvs/name-of-the-project/lib/python3.3/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/peter/.virtualenvs/name-of-the-project/lib/python3.3/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/peter/.virtualenvs/name-of-the-project/lib/python3.3/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/peter/.virtualenvs/name-of-the-project/lib/python3.3/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/peter/.virtualenvs/name-of-the-project/lib/python3.3/site-packages/cookiecutter/cli.py", line 123, in main
    default_config=default_config,
  File "/home/peter/.virtualenvs/name-of-the-project/lib/python3.3/site-packages/cookiecutter/main.py", line 91, in cookiecutter
    output_dir=output_dir
  File "/home/peter/.virtualenvs/name-of-the-project/lib/python3.3/site-packages/cookiecutter/generate.py", line 314, in generate_files
    shutil.copytree(indir, outdir)
  File "/home/peter/.virtualenvs/name-of-the-project/lib/python3.3/shutil.py", line 343, in copytree
    raise Error(errors)
shutil.Error: [('_/frameworks/Symfony/web/bundles/framework', '/home/peter/Development/repos/name-of-the-project/_/frameworks/Symfony/web/bundles/framework', "[Errno 21] Is a directory: '_/frameworks/Symfony/web/bundles/framework'")]
```
There is a bug report on the Python bug tracker for this issue: https://bugs.python.org/issue21697

According to https://github.com/pypa/pip/issues/1006#issuecomment-19890662  the error should go away if we set the `symlinks` parameter of `shutil.copytree()` to `True`.

Details on the cookiecutter and Python version I used  for the above stacktrace:  
``` bash
$ cookiecutter --version
Cookiecutter 1.5.1 from /home/peter/.virtualenvs/name-of-the-project/lib/python3.3/site-packages (Python 3.3)
```

**Comment by mforbes** [comment]
One can always do something manually with `hooks/post_gen_project.py`, for example:

```python
# hooks/post_gen_project.py
import os.path
import shutil
from collections import OrderedDict

def rm_rf(path):
    """Forcibly remove both files and directories, like `rm -rf`"""
    if os.path.isdir(path) and not os.path.islink(path):
        shutil.rmtree(path)
    elif os.path.exists(path):
        os.remove(path)


def make_symlinks():
    """Cookiecutter does not yet support symlinks, so we make them here.

    https://github.com/cookiecutter/cookiecutter/issues/865
    https://github.com/cookiecutter/cookiecutter/issues/1420
    """
    {% if cookiecutter._symlinks %}
    symlinks = {{ cookiecutter._symlinks }}
    for dest in symlinks:
        if os.path.exists(dest):
            rm_rf(dest)
        os.symlink(symlinks[dest], dest)
    {% endif %}


if __name__ == "__main__":
    make_symlinks()
```

This requires specifying the symlinks in the `cookiecutter.json` file:

```json
{
 "_symlinks": {
  "Docs/GettingStarted.md": "../GettingStarted.md",
  "Docs/README.md": "../README.md"}
}
```

for example.

My question: is there a way in `pre_gen_project.py` of scanning the template to see if there are symlinks, then populating these automatically?

**Comment by seanh** [comment]
_Symlinks become normal directories when cookiecutter is run_ I believe [this is the intended behavior](https://cookiecutter.readthedocs.io/en/stable/advanced/directories.html#organizing-cookiecutters-in-directories) of cookiecutter and we have cookiecutters that rely on this feature

**Comment by vit-zikmund** [comment]
Hello, I just found this old treasure and well, I have a yet another use case that seems like something I'd expect to be the default behavior 🙂:

Because when there's a symlink to a file, cookiecutter renders that symlink as a regular file, with the contents of the files the symplink pointed to  (flattens it). However this doesn't apply to symlinks to directories, which are rendered empty.

I'd expect to get the full contents of the directory, with all eventual further symlinks recursively done in the same fashion (unless there's a symlink loop, which I'd consider an error). What do you all think? Thanks a lot!

FYI @almarsk2
