### ISSUE TITLE
`self._name`,     ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by janssja** [audreyr/cookiecutter#874]
* Cookiecutter version: cookiecutter-1.5.0
* Template project url: https://github.com/pydanny/cookiecutter-django.git
* Python version: Python 2.7.10 (but also 3.5)
* Operating System: Mac OS X

### Description:
Syntax error when cloning

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/cookiecutter", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cookiecutter/cli.py", line 123, in main
    default_config=default_config,
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cookiecutter/main.py", line 82, in cookiecutter
    context['cookiecutter'] = prompt_for_config(context, no_input)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cookiecutter/prompt.py", line 193, in prompt_for_config
    env = StrictEnvironment(context=context)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cookiecutter/environment.py", line 70, in __init__
    **kwargs
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/cookiecutter/environment.py", line 37, in __init__
    **kwargs
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jinja2/environment.py", line 314, in __init__
    self.extensions = load_extensions(self, extensions)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jinja2/environment.py", line 85, in load_extensions
    extension = import_string(extension)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jinja2/utils.py", line 140, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jinja2_time/__init__.py", line 3, in <module>
    from .jinja2_time import TimeExtension
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jinja2_time/jinja2_time.py", line 3, in <module>
    import arrow
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/arrow/__init__.py", line 3, in <module>
    from .arrow import Arrow
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/arrow/arrow.py", line 11, in <module>
    from dateutil import tz as dateutil_tz
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dateutil/tz.py", line 78
    `self._name`,
    ^
SyntaxError: invalid syntax

```
after command:
```
cookiecutter https://github.com/pydanny/cookiecutter-django.git
```

**Comment by hackebrot** [comment]
Hi @janssja! 👋 

Can you please post the output for ``pip freeze`` here?

**Comment by janssja** [comment]
Solved after re-starting mac

**Comment by hackebrot** [comment]
😁

**Comment by FrankApiyo** [comment]
wow... i just had this exact same error.
lets see if restarting helps

**Comment by FrankApiyo** [comment]
didn't work... i had to start another virtual env and copy my files over. The strange thing is that when i pip freeze, i see almost all the packages installed in my computer and not just in my venv

**Comment by hackebrot** [comment]
Hey @FrankApiyo! 👋

I suggest raising this issue with the `dateutil` project? According to the above stacktrace that's where the SyntaxError is raised?

**Comment by pydanny** [comment]
In the 1.7 release of Cookiecutter (hopefully out next week), `dateutil` has been replaced with a different project. This problem will hopefully no longer exist.
