### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable when starting a project

### ISSUE THREAD

**Issue by plus500s** [audreyr/cookiecutter#928]
* Cookiecutter version: 1.5.1
* Template project url: https://github.com/pydanny/cookiecutter-django
* Python version: Python 3.5.3 (default, Jan 26 2017, 13:12:44)
* Operating System: OSX

### Description:
Got the following after

`cookiecutter https://github.com/pydanny/cookiecutter-django`
Relevant issue posted https://github.com/pydanny/cookiecutter-django/issues/1118 
```
Traceback (most recent call last):
  File "/Users/captain/PycharmProjects/a8/.venv/bin/cookiecutter", line 11, in <module>
    sys.exit(main())
  File "/Users/captain/PycharmProjects/a8/.venv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/captain/PycharmProjects/a8/.venv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/captain/PycharmProjects/a8/.venv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/captain/PycharmProjects/a8/.venv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/captain/PycharmProjects/a8/.venv/lib/python3.5/site-packages/cookiecutter/cli.py", line 123, in main
    default_config=default_config,
  File "/Users/captain/PycharmProjects/a8/.venv/lib/python3.5/site-packages/cookiecutter/main.py", line 91, in cookiecutter
    output_dir=output_dir
  File "/Users/captain/PycharmProjects/a8/.venv/lib/python3.5/site-packages/cookiecutter/generate.py", line 349, in generate_files
    generate_file(project_dir, infile, context, env)
  File "/Users/captain/PycharmProjects/a8/.venv/lib/python3.5/site-packages/cookiecutter/generate.py", line 153, in generate_file
    if is_binary(infile):
  File "/Users/captain/PycharmProjects/a8/.venv/lib/python3.5/site-packages/binaryornot/check.py", line 25, in is_binary
    return is_binary_string(chunk)
  File "/Users/captain/PycharmProjects/a8/.venv/lib/python3.5/site-packages/binaryornot/helpers.py", line 96, in is_binary_string
    if (detected_encoding['confidence'] > 0.9
TypeError: 'NoneType' object is not subscriptable

```
### What I've run:

```
cookiecutter https://github.com/pydanny/cookiecutter-django
```

**Comment by pydanny** [comment]
This has to do with breaking changes in `chardet`. Please do:

```
pip install -U "chardet<3.0"
```

We hope to have a new release of Cookiecutter out soon that addresses this problem.

**Comment by pydanny** [comment]
`binaryornot` and `chardet` have been updated to address this situation. I'll see about pushing downstream implementations such as Conda and Homebrew.
