### ISSUE TITLE
template directory with pipe breaks on windows

### ISSUE THREAD

**Issue by Vampire** [audreyr/cookiecutter#943]
* Cookiecutter version: 1.5.1
* Template project url: gh:vintasoftware/cookiecutter-tapioca
* Python version: 3.5
* Operating System: Windows Python called from Cygwin

### Description:

Somehow the pipe character in the filename (not the best idea probably) somehow gets read as `\uf07c` which then of course is not correctly parsed.

### What I've run:

```
~ $ /c/Program\ Files/Python35/Scripts/cookiecutter gh:vintasoftware/cookiecutter-tapioca <<< $'\n\n\n\n\n\n\n\n\n'
You've cloned D:\Programme\cygwin\home\bkautler\.cookiecutters\cookiecutter-tapioca before. Is it okay to delete and re-clone it? [yes]: service_name [The Name Of The Service Being Wrapped]: api_root_url [url to the root of the api]: full_name [Filipe Ximenes]: email [filipeximenes@gmail.com]: github_username [filipeximenes]: version [0.1]: use_oauth_2 [n]: use_oauth_1 [n]: use_basic_auth [n]: Traceback (most recent call last):
  File "c:\program files\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python35\Scripts\cookiecutter.exe\__main__.py", line 9, in <module>
  File "c:\program files\python35\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files\python35\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\program files\python35\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files\python35\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\program files\python35\lib\site-packages\cookiecutter\cli.py", line 123, in main
    default_config=default_config,
  File "c:\program files\python35\lib\site-packages\cookiecutter\main.py", line 91, in cookiecutter
    output_dir=output_dir
  File "c:\program files\python35\lib\site-packages\cookiecutter\generate.py", line 253, in generate_files
    template_dir = find_template(repo_dir)
  File "c:\program files\python35\lib\site-packages\cookiecutter\find.py", line 29, in find_template
    print(project_template)
  File "c:\program files\python35\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\uf07c' in position 35: character maps to <undefined>
```

**Comment by hackebrot** [comment]
Hi @Vampire! 👋 

I'm not sure what we can do about this. Any ideas @filipeximenes?

**Comment by Vampire** [comment]
There are many possibilities. For example change the conventions, so that only portable characters are used in the patterns, or do not have the pattern in the name, but in a file as text, or work around the encoding issue by handling the special cases. :-)

**Comment by hackebrot** [comment]
Right, but "only portable characters in patterns" and "no patterns in the name" fall under the responsibility of template authors. 🤔 

I can't seem to find the line from your traceback that is causing the issue, neither on 1.5.1 nor master. Does the same problem occur with master on your setup?

**Comment by filipeximenes** [comment]
Oh, so the 'pipes' are the issue. I didn't know that this was going to break on Windows. The only thing that comes to mind from cookiecutter-tapioca side is to stop doing operations in file names. The downside is that it will need to instruct users how to write the name in the correct format.

**Comment by Vampire** [comment]
@hackebrot I just tried with `master` and it is happening just the same here. This is the workaround I used to get the tapioca one working here: ecb6db9d22231262dc5a03891cf668631bad9dc9. But this only handles pipe characters, I don't know whether there may be other characters affected or whether this is a good workaround in general. It just worked for me for this one case I tested.

You said

> but "only portable characters in patterns" and "no patterns in the name" fall under the responsibility of template authors.

but that is not fully true in my opinion. If you look at the tapioca repo, they have a directory called `tapioca_{{cookiecutter.service_name|lower|replace(' ', '_')}}`. Obviously this is supported by cookiecutter as it works on Linux and with my workaround for the encoding problem on Windows. My suggestion was to either support only characters that are supported by all thinkable file systems and OS properly, or (as this might be pretty hard or impossible) to deprecate using patterns like this in file and folder names and instead support some file to contain the pattern for this. E. g. you could add the convention that if you have some file or directory called `foo.bar` and besides it a file called `foo.bar.cookiecutter.pattern` which is a text file that contains `tapioca_{{cookiecutter.service_name|lower|replace(' ', '_')}}`. This way you will never have problems with special characters in directory or file names that are encoded wrongly on directory listing. Btw. with Git for windows I cannot even clone the `cookiecutter-tapioca` repository, or to be more correct I can clone it, but the checkout fails. With Cygwin Git it works.

**Comment by pydanny** [comment]
This is a limitation of Windows and outside the scope of Cookiecutter. There's literally nothing we can do lunch.

I advise this ticket be closed and a now put into the documentation about the limitations of Windows forwardness filenames and social characters.

**Comment by Vampire** [comment]
@pydanny why is there "literally nothing you can do"? I suggested a fix which does not seem to be too bad in my opinion and probably easily implementable.

**Comment by iedmrc** [comment]
Any updates on this?

**Comment by RichardSTote** [comment]
I think you better update your readme and say not fully Cross Platform
