### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str' on Python 3.6.2

### ISSUE THREAD

**Issue by bofm** [audreyr/cookiecutter#983]
* Cookiecutter version: 1.5.1
* Template project url: https://github.com/audreyr/cookiecutter-pypackage.git
* Python version: 3.6.2
* Operating System: Mac OS Sierra

### Description:

When git clone subcommand fails the following error is returned.
### What I've run:

```bash
$ mkdir x
$ cd x
$ pip3 freeze|grep coo
cookiecutter==1.5.1
$ env|egrep 'LC|LAN'
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
LC_CTYPE=UTF-8
$ cookiecutter https://github.com/audreyr/cookiecutter-pypackage.git
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cookiecutter/vcs.py", line 123, in clone
    stderr=subprocess.STDOUT,
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'clone', 'https://github.com/audreyr/cookiecutter-pypackage.git']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/cookiecutter", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/cookiecutter/cli.py", line 123, in main
    default_config=default_config,
  File "/usr/local/lib/python3.6/site-packages/cookiecutter/main.py", line 63, in cookiecutter
    no_input=no_input,
  File "/usr/local/lib/python3.6/site-packages/cookiecutter/repository.py", line 84, in determine_repo_dir
    no_input=no_input,
  File "/usr/local/lib/python3.6/site-packages/cookiecutter/vcs.py", line 132, in clone
    if 'not found' in clone_error.output.lower():
TypeError: a bytes-like object is required, not 'str'
```

A better error message should be displayed instead.

**Comment by michaeljoseph** [comment]
Hi @bofm, thanks for the issue, this looks like #905, which is in master, but not yet released.

**Comment by ymcidence** [comment]
Is there anybody sloved this ?
